pipeline {

    agent { label 'docker' }

    environment {
        GIT_REPO = 'https://github.com/Dhananjayakl/docker_jenkins_task.git'
        BRANCH = 'main'
        IMAGE_NAME = "devops-node-app"
        DOCKERHUB_USERNAME = "dhananjay93"
    }

    stages {

        stage('Clone') {
            steps {
                git branch: BRANCH, url: GIT_REPO
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('assignment-7') {
                    sh 'docker build -t $IMAGE_NAME:latest .'
                }
            }
        }

        stage('Create Docker Network') {
            steps {
                sh 'docker network create app-network || true'
            }
        }

        stage('Run Compose') {
            steps {
                dir('assignment-7') {
                    sh '''
                    docker compose down || true
                    docker compose up -d
                    '''
                }
            }
        }

        stage('Docker Login') {
            steps {
                    sh 'docker login -u dhananjay93 -p dhanu2545'
                }
            }

        stage('Push Image') {
            steps {
                sh 'docker tag $IMAGE_NAME $DOCKERHUB_USERNAME/$IMAGE_NAME:latest'
                sh 'docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest'
            }
        }

    }

}