pipeline {
    agent {
        label 'docker'
    }

    environment {
        GIT_REPO = 'https://github.com/Dhananjayakl/docker_jenkins_task.git'
        BRANCH = 'main'
        IMAGE_NAME = 'project-5-rust'
    }

    stages {
        stage('Clone') {
            steps {
                git branch: BRANCH, url: GIT_REPO
            }
        }

        stage('Build') {
            steps {
                dir('project-5-10-03') {
                    sh 'sudo docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Run') {
            steps {
                dir('project-5-10-03') {
                    sh 'sudo docker run -d --name $IMAGE_NAME -p 80:80 $IMAGE_NAME'
                }
            }
        }

        stage('Push') {
            steps {
                sh 'sudo docker tag $IMAGE_NAME dhananjay93/$IMAGE_NAME'
                sh 'sudo docker push dhananjay93/$IMAGE_NAME'
            }
        }
    }
}